---
before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes yamllint shellcheck make inkscape webp optipng
lint:
  script:
    - yamllint .gitlab-ci.yml
    - shellcheck -x prebuild.sh build.sh
rasterize:
  script:
    - make -C fenix-artwork -B -j`nproc`
