name: Build Fennec

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Fdroidserver
        run: |
          sudo apt update -y
          sudo apt install pipx
          pipx ensurepath
          sudo pipx ensurepath --global
          pipx install git+https://gitlab.com/fdroid/fdroidserver
      
      - name: Cache F-Droid data
        id: cache-fdroiddata
        uses: actions/cache@v4
        with:
          path: fdroiddata
          key: ${{ runner.os }}-fdroiddata

      - name: Clone F-Droid data
        if: steps.cache-fdroiddata.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          repository: f-droid/fdroiddata

      - name: Pull F-Droid data
        if: steps.cache-fdroiddata.outputs.cache-hit == 'true'
        run: git -C fdroiddata pull

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "zulu"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install NDK
        run: sdkmanager "ndk;26.2.11394342"

      - name: Cache F-Droid build srclib
        id: cache-build-srclib
        uses: actions/cache@v4
        with:
          path: fdroiddata/build/srclib
          key: ${{ runner.os }}-srclib

      - name: Build
        run: cd fdroiddata && fdroid build org.mozilla.fennec_fdroid:1290020 -v
