name: Build Fennec

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Fdroidserver
        run: sudo apt update -y && \
          sudo apt install pipx && \
          pipx ensurepath && \
          sudo pipx ensurepath --global && \
          pipx install https://gitlab.com/fdroid/fdroidserver

      - name: Clone Fdroiddata
        run: git clone https://gitlab.com/fdroid/fdroiddata

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build
        run: cd fdroiddata && fdroid build org.mozilla.fennec_fdroid:1290020 -v



